### ISSUE TITLE
Perhaps more a Windows quarto problem

### ISSUE THREAD

**Issue by dar143** [mcanouil/quarto-invoice#4]
>quarto add extension mcanouil/quarto-invoice
ERROR: Too many arguments: mcanouil/quarto-invoice

Stack trace:
    at Command.parseArguments (file:///C:/Program%20Files/Quarto/bin/quarto.js:8268:27)
    at Command.parseCommand (file:///C:/Program%20Files/Quarto/bin/quarto.js:7987:31)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async quarto (file:///C:/Program%20Files/Quarto/bin/quarto.js:114968:5)
    at async file:///C:/Program%20Files/Quarto/bin/quarto.js:114986:9

**Comment by mcanouil** [comment]
Which version of Quarto are you using? `quarto --version`

**Comment by dar143** [comment]
Sorry I should have included that
Quart version is 1.4.549

**Comment by mcanouil** [comment]
Do you have the issue with other extensions?
If so, please open an issue on <https://github.com/quarto-dev/quarto-cli/>.

**Comment by mcanouil** [comment]
Oh actually, there was a change in Quarto CLI.
"extension" is no longer in use in the command.

**Comment by mcanouil** [comment]
I updated the command (#5).
Thanks for the report.

**Comment by dar143** [comment]
Great . Works.
In which directory is the extension looking for any logo's
I tried the same as my invoice qmd file and it didn;t
________________________________
