### ISSUE TITLE
How to use this in conjunction with generate_quarto_invoices

### ISSUE THREAD

**Issue by chalg** [mcanouil/quarto-invoice#8]
I'm running Python 3.11.5 on Windows. I'm able to render the example template into a PDF, which looks good. I'm just trying to work out how to now inject variables, so I assume I should instead use the template.qmd from the generate_quarto_invoices repo? I have tried this but it is falling over at the `subprocess.run` point.

`Command '['quarto', 'render', 'template.qmd', '--metadata-file', 'input/202406-001.yml', '--output', 'output/INVOICE-N202406-001-Voyager Renewables.pdf']' returned non-zero exit status 1.`

So it is creating the yml file as expected but is having an issue with rendering.

Also under Usage in the [generate_quarto_invoices](https://github.com/chalg/generate_quarto_invoices)

generate-invoices.py \
  --name="Consulting" \
  --task="A very important job" \
  --details="A description of the tasks" \
  --amount="1,234.56" \
  --recipient="Company-Inc" \
  --first="2024-01-15"\
  --last="2024-01-31" \
  --template="template.qmd"

Is the above supposed to be run at the terminal?

**Comment by chalg** [comment]
Ok got it working with a generic function. Now just need to update some formatting for Australia, e.g. currency. If I try and change the Euro to a dollar, I get errors. Do I need to make updates in the _extensions folder for the .typ files?

**Comment by mcanouil** [comment]
This repository is a demo repository to show how to generate several documents out of one single Quarto document using YAML key/values.

This repository uses a Quarto extension format:

- https://github.com/mcanouil/quarto-invoice

See the documentation about extensions:

- https://quarto.org/docs/extensions/listing-formats.html

See the documentation about custom Typst format:

- https://quarto.org/docs/output-formats/typst-custom.html
